_wandb:
    value:
        cli_version: 0.22.0
        e:
            srdygryaa43j3x7ponf5hws6zhppq8rm:
                codePath: task2_video_segmentation.ipynb
                codePathLocal: task2_video_segmentation.ipynb
                cpu_count: 24
                cpu_count_logical: 32
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "1021821579264"
                        used: "357363851264"
                email: junichi.ocena1021@gmail.com
                executable: C:\Users\junic\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe
                git:
                    remote: https://github.com/nrsjun/MachineLearning-LVEF.git
                gpu: NVIDIA GeForce RTX 4070 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 4608
                      memoryTotal: "8585740288"
                      name: NVIDIA GeForce RTX 4070 Laptop GPU
                      uuid: GPU-eccc52bb-6a1c-032a-4003-40378fe1447e
                host: Jun
                memory:
                    total: "34141495296"
                os: Windows-11-10.0.26100-SP0
                program: c:\Users\junic\Desktop\University\MachineLearning\echonet\task2_video_segmentation.ipynb
                python: CPython 3.13.7
                root: c:\Users\junic\Desktop\University\MachineLearning\echonet
                startedAt: "2025-09-28T02:45:53.432865Z"
                writerId: srdygryaa43j3x7ponf5hws6zhppq8rm
        m: []
        python_version: 3.13.7
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 16
            "4": 3.13.7
            "5": 0.22.0
            "8":
                - 1
                - 3
            "12": 0.22.0
            "13": windows-amd64
architecture:
    value: U-Net
batch_size:
    value: 16
dataset:
    value: EchoNet-Dynamic
epochs:
    value: 30
learning_rate:
    value: 0.001
loss:
    value: BCE+Dice
optimizer:
    value: AdamW
patience:
    value: 8
scheduler:
    value: CosineAnnealingLR
